//-------------------------------------------------------------------------
//// SPI Register Map - Auto-generated Verilog Defines    
//-------------------------------------------------------------------------

`define SPI_DATA_WIDTH 32
`define SPI_ADDR_WIDTH 32
`define SPI_REG_WIDTH  32
`define SPI_BASE_ADDR  'h3500_0000

// --------------------------
// Register Addresses
// --------------------------

`define SPI_CONTROL_REGISTER1_ADDR 'h0
`define SPI_CONTROL_REGISTER2_ADDR 'h1
`define SPI_BAUD_RATE_REGISTER_ADDR 'h2
`define SPI_STATUS_REGISTER_ADDR 'h3
`define SPI_DATA_REGISTER_ADDR 'h4
`define SPI_COMMAND_REGISTER_ADDR 'h5

// --------------------------
// Register Reset Values
// --------------------------

`define SPI_CONTROL_REGISTER1_RST 32'h0
`define SPI_CONTROL_REGISTER2_RST 32'h10
`define SPI_BAUD_RATE_REGISTER_RST 32'h0
`define SPI_STATUS_REGISTER_RST 32'h0
`define SPI_DATA_REGISTER_RST 32'h0
`define SPI_COMMAND_REGISTER_RST 32'h0

// --------------------------
// Register Mask Values
// --------------------------

`define SPI_CONTROL_REGISTER1_MASK 32'hff
`define SPI_CONTROL_REGISTER2_MASK 32'h7f
`define SPI_BAUD_RATE_REGISTER_MASK 32'h77
`define SPI_STATUS_REGISTER_MASK 32'hb0
`define SPI_DATA_REGISTER_MASK 32'hffffffff
`define SPI_COMMAND_REGISTER_MASK 32'h7

// --------------------------
// Vector Output Widths
// --------------------------

`define SPI_SAMPLE_O_WIDTH 3
`define SPI_SPPR_O_WIDTH 3
`define SPI_SPR_O_WIDTH 3
`define SPI_DATA_O_WIDTH 32

// --------------------------
// Register Bit Positions
// --------------------------

//---------------- CONTROL_REGISTER1 -----------
`define SPI_CONTROL_REGISTER1_SPIE_POS 7
`define SPI_CONTROL_REGISTER1_SPE_POS 6
`define SPI_CONTROL_REGISTER1_SPTIE_POS 5
`define SPI_CONTROL_REGISTER1_MSTR_POS 4
`define SPI_CONTROL_REGISTER1_CPOL_POS 3
`define SPI_CONTROL_REGISTER1_CPHA_POS 2
`define SPI_CONTROL_REGISTER1_SSOE_POS 1
`define SPI_CONTROL_REGISTER1_LSBFE_POS 0

//---------------- CONTROL_REGISTER2 -----------
`define SPI_CONTROL_REGISTER2_MODFEN_POS 3
`define SPI_CONTROL_REGISTER2_BIDIROE_POS 2
`define SPI_CONTROL_REGISTER2_SPISWAI_POS 1
`define SPI_CONTROL_REGISTER2_SPC0_POS 0
`define SPI_CONTROL_REGISTER2_SAMPLE2_POS 6
`define SPI_CONTROL_REGISTER2_SAMPLE1_POS 5
`define SPI_CONTROL_REGISTER2_SAMPLE0_POS 4

//---------------- BAUD_RATE_REGISTER -----------
`define SPI_BAUD_RATE_REGISTER_SPPR2_POS 6
`define SPI_BAUD_RATE_REGISTER_SPPR1_POS 5
`define SPI_BAUD_RATE_REGISTER_SPPR0_POS 4
`define SPI_BAUD_RATE_REGISTER_SPR2_POS 2
`define SPI_BAUD_RATE_REGISTER_SPR1_POS 1
`define SPI_BAUD_RATE_REGISTER_SPR0_POS 0

//---------------- STATUS_REGISTER -----------
`define SPI_STATUS_REGISTER_SPIF_POS 7
`define SPI_STATUS_REGISTER_SPTEF_POS 5
`define SPI_STATUS_REGISTER_MODF_POS 4

//---------------- DATA_REGISTER -----------
`define SPI_DATA_REGISTER_DATA31_POS 31
`define SPI_DATA_REGISTER_DATA30_POS 30
`define SPI_DATA_REGISTER_DATA29_POS 29
`define SPI_DATA_REGISTER_DATA28_POS 28
`define SPI_DATA_REGISTER_DATA27_POS 27
`define SPI_DATA_REGISTER_DATA26_POS 26
`define SPI_DATA_REGISTER_DATA25_POS 25
`define SPI_DATA_REGISTER_DATA24_POS 24
`define SPI_DATA_REGISTER_DATA23_POS 23
`define SPI_DATA_REGISTER_DATA22_POS 22
`define SPI_DATA_REGISTER_DATA21_POS 21
`define SPI_DATA_REGISTER_DATA20_POS 20
`define SPI_DATA_REGISTER_DATA19_POS 19
`define SPI_DATA_REGISTER_DATA18_POS 18
`define SPI_DATA_REGISTER_DATA17_POS 17
`define SPI_DATA_REGISTER_DATA16_POS 16
`define SPI_DATA_REGISTER_DATA15_POS 15
`define SPI_DATA_REGISTER_DATA14_POS 14
`define SPI_DATA_REGISTER_DATA13_POS 13
`define SPI_DATA_REGISTER_DATA12_POS 12
`define SPI_DATA_REGISTER_DATA11_POS 11
`define SPI_DATA_REGISTER_DATA10_POS 10
`define SPI_DATA_REGISTER_DATA09_POS 9
`define SPI_DATA_REGISTER_DATA08_POS 8
`define SPI_DATA_REGISTER_DATA07_POS 7
`define SPI_DATA_REGISTER_DATA06_POS 6
`define SPI_DATA_REGISTER_DATA05_POS 5
`define SPI_DATA_REGISTER_DATA04_POS 4
`define SPI_DATA_REGISTER_DATA03_POS 3
`define SPI_DATA_REGISTER_DATA02_POS 2
`define SPI_DATA_REGISTER_DATA01_POS 1
`define SPI_DATA_REGISTER_DATA00_POS 0

//---------------- COMMAND_REGISTER -----------
`define SPI_COMMAND_REGISTER_START_POS 2
`define SPI_COMMAND_REGISTER_CLEAR_POS 1
`define SPI_COMMAND_REGISTER_ABORT_POS 0

